### ISSUE TITLE
use static PLUGIN instead of const PLUGIN

### ISSUE THREAD

**Issue by vincentfretin** [foxford/janus-conference#145]
Hi @Leonqn @feymartynov while reading your plugin code, I see you also have `const PLUGIN` like we did before in janus-plugin-sfu, we changed that to `static PLUGIN`. You may want a similar change in janus-conference, see the comment there https://github.com/mozilla/janus-plugin-sfu/pull/69

and https://doc.rust-lang.org/std/keyword.const.html

> const items looks remarkably similar to static items, which introduces some confusion as to which one should be used at which times. To put it simply, constants are inlined wherever they’re used, making using them identical to simply replacing the name of the const with its value. Static variables, on the other hand, point to a single location in memory, which all accesses share. This means that, unlike with constants, they can’t have destructors, and act as a single value across the entire codebase.

**Comment by Leonqn** [comment]
Hi! Thanks for the advice, will change.
